create table tblSugang (
          sugangSeq number not null primary key,
          memberSeq number not null references tblStudent(memberSeq),
          openCourseSeq number references tblOpenCourse(openCourseSeq)
);
select * from TBLOPENCOURSE;
drop table tblSugang;

create sequence seqSugang;
drop sequence seqSugang;
select * from TBLSTUDENT;

create sequence seqMember start with 14;
drop sequence seqMember;

insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,37); --37번 openCourse 30명
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,38); --38 openCourse 30명
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,39); --39번 30명
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,40); --40번 26명
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,41); --41번 26명

insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42);
insert into tblSugang (sugangSeq, memberSeq, openCourseSeq) VALUES (seqSugang.nextval,seqMember.nextval,42); --42번 26명

insert into tblSugang (sugangSeq, memberSeq) VALUES (seqSugang.nextval,seqMember.nextval);
insert into tblSugang (sugangSeq, memberSeq) VALUES (seqSugang.nextval,seqMember.nextval);
insert into tblSugang (sugangSeq, memberSeq) VALUES (seqSugang.nextval,seqMember.nextval);
insert into tblSugang (sugangSeq, memberSeq) VALUES (seqSugang.nextval,seqMember.nextval);
insert into tblSugang (sugangSeq, memberSeq) VALUES (seqSugang.nextval,seqMember.nextval);
insert into tblSugang (sugangSeq, memberSeq) VALUES (seqSugang.nextval,seqMember.nextval);
insert into tblSugang (sugangSeq, memberSeq) VALUES (seqSugang.nextval,seqMember.nextval);
insert into tblSugang (sugangSeq, memberSeq) VALUES (seqSugang.nextval,seqMember.nextval);
insert into tblSugang (sugangSeq, memberSeq) VALUES (seqSugang.nextval,seqMember.nextval);
insert into tblSugang (sugangSeq, memberSeq) VALUES (seqSugang.nextval,seqMember.nextval);
insert into tblSugang (sugangSeq, memberSeq) VALUES (seqSugang.nextval,seqMember.nextval);
insert into tblSugang (sugangSeq, memberSeq) VALUES (seqSugang.nextval,seqMember.nextval);
insert into tblSugang (sugangSeq, memberSeq) VALUES (seqSugang.nextval,seqMember.nextval);
insert into tblSugang (sugangSeq, memberSeq) VALUES (seqSugang.nextval,seqMember.nextval);
insert into tblSugang (sugangSeq, memberSeq) VALUES (seqSugang.nextval,seqMember.nextval);
insert into tblSugang (sugangSeq, memberSeq) VALUES (seqSugang.nextval,seqMember.nextval);
insert into tblSugang (sugangSeq, memberSeq) VALUES (seqSugang.nextval,seqMember.nextval);
insert into tblSugang (sugangSeq, memberSeq) VALUES (seqSugang.nextval,seqMember.nextval);
insert into tblSugang (sugangSeq, memberSeq) VALUES (seqSugang.nextval,seqMember.nextval);

select count(*) from tblSugang where openCourseSeq=37;
select * from tblSugang;
select count(*) from TBLMEMBER;